[build]
  command = "npm install && npm run build"
  publish = "dist"
  base = "."

[build.environment]
  NODE_VERSION = "18"

# Proxy API requests to the backend
[[redirects]]
  from = "/api/chat"
  to = "https://math-gpt.onrender.com/chat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Redirect all other requests to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  except = ["/api/*"] 