services:
  - type: web
    name: math-gpt-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false  # You'll need to set this manually in Render's dashboard
    healthCheckPath: /chat
    autoDeploy: true 